{{- if .Values.global.gke.enabled -}}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: "{{ .Chart.Name }}-monitoring"
spec:
  selector:
    matchLabels:
      app: "{{ include "sync.name" . }}"
  endpoints:
    - port: http
      interval: 30s
{{- end }}
