{{- if .Values.gke.enabled -}}
apiVersion: monitoring.googleapis.com/v1
kind: ClusterPodMonitoring
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
    - port: http
      interval: 30s
{{- end }}
