# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: macOS-13

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'fromFile'
      versionFilePath: '.nvmrc'
    displayName: 'Install Node.js'

  - script: |
      yarn install --immutable --inline-builds
    displayName: 'yarn install'
