# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  yarn_config_cache: $(Pipeline.Workspace)/.yarn/cache

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'fromFile'
      versionFilePath: '.nvmrc'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      path: $(yarn_config_cache)
    displayName: Cache yarn

  - script: |
      yarn install --immutable --inline-builds
    displayName: 'yarn install'

  - script: |
      yarn nx build @affine/web
    displayName: 'yarn build @affine/web'
